### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by r0fls**
typo

### CODE REVIEW

**Comment by timothysc** [comment]
@r0fls We use DCO to signoff commits, would it be possible to `git commit --signoff` your commit

**Comment by r0fls** [comment]
Hmm 🤔  I don't know how `--signoff` works, it's not doing anything for me:

```
$ git commit --signoff
On branch patch-1
Your branch is up-to-date with 'origin/patch-1'.

nothing to commit, working tree clean
```

**Comment by liztio** [comment]
try `git commit --amend --signoff`. It'll amend your old commit with the
signoff. Then push the changes up with `git push --force-with-lease`

**Comment by timothysc** [comment]
Thx for the patch!

**Pull request merged**
