### PR TITLE
Updates to use dep against 1.8/5.0.0 client

### PR DESCRIPTION
**Pull request by timothysc**
Signed-off-by: Timothy St. Clair <timothysc@gmail.com>

Partially addresses #17 but also rev's to latest client in prep for 0.9.0 release.   I'll look at the tests for sanity.

### CODE REVIEW

**Comment by timothysc** [comment]
@ncdc could you verify the .toml is sane according to api-machinery version(s)?

**Comment by ncdc** [comment]
@timothysc will do, although it might have to wait until tomorrow morning. Also, did you run `dep prune`? You might find https://github.com/heptio/ark/blob/master/hack/dep-save.sh worthwhile.

**Comment by timothysc** [comment]
@ncdc just did, and it cut the deps to 1/4 the original size.  Thx!

**Comment by timothysc** [comment]
Timeline is crunched a bit, I'm going to merge but if you spot something please let us know.

**Pull request merged**
