### PR TITLE
Update Go to v1.13

### LINKED ISSUE #870: Update go version to latest 1.12 patch

### PR DESCRIPTION
**Pull request by zubron**
Update the build image and also the Go version in Travis.

**Which issue(s) this PR fixes**
- Fixes #870

### CODE REVIEW

**Comment by johnSchnake** [comment]
All seems good on CI; do you have any reason to think this isn't ready to go?

**Comment by zubron** [comment]
Nope, I'll merge this. I made it a draft PR to try it out and make sure that things were working as expected.

**Comment by johnSchnake** [comment]
I approved but I actually just remembered that I think you need to update the README with the recommended Go version.

**Comment by johnSchnake** [comment]
Dont forget to squash

**Pull request merged**
